"""Initial migration

Revision ID: bb799a9b9ba1
Revises: 19762ae2189c
Create Date: 2026-02-01 00:25:17.075324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb799a9b9ba1'
down_revision = '19762ae2189c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
